// Code generated by "stringer -type=GenerateStatus -linecomment -output generate_status_string.go"; DO NOT EDIT.

package consts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Waiting-1]
	_ = x[Executing-2]
	_ = x[Generated-3]
	_ = x[Reviewing-4]
	_ = x[Success-5]
	_ = x[Failure-6]
	_ = x[Expired-10]
}

const (
	_GenerateStatus_name_0 = "1:等待执行2:执行中3:已生图4:审核中5:成功6:失败"
	_GenerateStatus_name_1 = "10:任务已过期(自定义)"
)

var (
	_GenerateStatus_index_0 = [...]uint8{0, 14, 25, 36, 47, 55, 63}
)

func (i GenerateStatus) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _GenerateStatus_name_0[_GenerateStatus_index_0[i]:_GenerateStatus_index_0[i+1]]
	case i == 10:
		return _GenerateStatus_name_1
	default:
		return "GenerateStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
