// Code generated by "stringer -type=Preprocessor -linecomment -output preprocessor_string.go"; DO NOT EDIT.

package consts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Canny-1]
	_ = x[DepthMidas-2]
	_ = x[DepthLeres-3]
	_ = x[DepthLeresPlus-4]
	_ = x[HED-5]
	_ = x[HEDSafe-6]
	_ = x[NormalMap-9]
	_ = x[MediaPipeFace-7]
	_ = x[OpenPose-10]
	_ = x[OpenPoseHand-11]
	_ = x[OpenPoseFace-12]
	_ = x[OpenPoseFaceOnly-13]
	_ = x[OpenPoseFull-14]
	_ = x[MLSD-8]
	_ = x[PIDINET-17]
	_ = x[PIDINETSafe-18]
	_ = x[SoftEdgeTeed-58]
	_ = x[SoftEdgeAnyline-65]
	_ = x[ScribblePIDINET-20]
	_ = x[ScribbleXdog-21]
	_ = x[ScribbleHED-22]
	_ = x[LineartRealistic-29]
	_ = x[LineartStandard-32]
	_ = x[LineartCoarse-30]
	_ = x[LineartAnime-31]
	_ = x[LineartAnimeDenoise-36]
	_ = x[DepthZoe-25]
	_ = x[DepthHandRefiner-57]
	_ = x[DepthAnything-64]
	_ = x[Segmentation-23]
	_ = x[OneFormerCoco-27]
	_ = x[OneFormerAde20k-28]
	_ = x[AnimeFaceSegment-54]
	_ = x[NormalBae-26]
	_ = x[DensePose-55]
	_ = x[DensePoseParula-56]
	_ = x[TileResample-34]
	_ = x[TileColorfix-43]
	_ = x[TileColorfixSharp-44]
	_ = x[BlurGaussian-52]
	_ = x[ReferenceOnly-37]
	_ = x[ReferenceAdain-38]
	_ = x[ReferenceAdainAttn-39]
	_ = x[IPAdapterClipSd15-48]
	_ = x[IPAdapterClipSdxl-49]
	_ = x[IPAdapterClipSdxlPlusVith-61]
	_ = x[ClipVision-15]
	_ = x[Color-16]
	_ = x[PIDINETSketch-19]
	_ = x[Shuffle-33]
	_ = x[RecolorLuminance-50]
	_ = x[RecolorIntensity-51]
	_ = x[InpaintGlobalHarmonious-40]
	_ = x[InpaintOnly-41]
	_ = x[InpaintOnlyLama-42]
	_ = x[IPAdapterFaceId-62]
	_ = x[IPAdapterFaceIdPlus-63]
	_ = x[InstantIDFaceKeypoints-59]
	_ = x[InstantIDFaceEmbedding-60]
	_ = x[Invert-35]
}

const (
	_Preprocessor_name_0 = "0CannyDepthMidasDepthLeresDepthLeresPlusHEDHEDSafeMediaPipeFaceMLSDNormalMapOpenPoseOpenPoseHandOpenPoseFaceOpenPoseFaceOnlyOpenPoseFullClipVisionColorPIDINETPIDINETSafePIDINETSketchScribblePIDINETScribbleXdogScribbleHEDSegmentation"
	_Preprocessor_name_1 = "DepthZoeNormalBaeOneFormerCocoOneFormerAde20kLineartRealisticLineartCoarseLineartAnimeLineartStandardShuffleTileResampleInvertLineartAnimeDenoiseReferenceOnlyReferenceAdainReferenceAdainAttnInpaintGlobalHarmoniousInpaintOnlyInpaintOnlyLamaTileColorfixTileColorfixSharp"
	_Preprocessor_name_2 = "IPAdapterClipSd15IPAdapterClipSdxlRecolorLuminanceRecolorIntensityBlurGaussian"
	_Preprocessor_name_3 = "AnimeFaceSegmentDensePoseDensePoseParulaDepthHandRefinerSoftEdgeTeedInstantIDFaceKeypointsInstantIDFaceEmbeddingIPAdapterClipSdxlPlusVithIPAdapterFaceIdIPAdapterFaceIdPlusDepthAnythingSoftEdgeAnyline"
)

var (
	_Preprocessor_index_0 = [...]uint8{0, 1, 6, 16, 26, 40, 43, 50, 63, 67, 76, 84, 96, 108, 124, 136, 146, 151, 158, 169, 182, 197, 209, 220, 232}
	_Preprocessor_index_1 = [...]uint16{0, 8, 17, 30, 45, 61, 74, 86, 101, 108, 120, 126, 145, 158, 172, 190, 213, 224, 239, 251, 268}
	_Preprocessor_index_2 = [...]uint8{0, 17, 34, 50, 66, 78}
	_Preprocessor_index_3 = [...]uint8{0, 16, 25, 40, 56, 68, 90, 112, 137, 152, 171, 184, 199}
)

func (i Preprocessor) String() string {
	switch {
	case 0 <= i && i <= 23:
		return _Preprocessor_name_0[_Preprocessor_index_0[i]:_Preprocessor_index_0[i+1]]
	case 25 <= i && i <= 44:
		i -= 25
		return _Preprocessor_name_1[_Preprocessor_index_1[i]:_Preprocessor_index_1[i+1]]
	case 48 <= i && i <= 52:
		i -= 48
		return _Preprocessor_name_2[_Preprocessor_index_2[i]:_Preprocessor_index_2[i+1]]
	case 54 <= i && i <= 65:
		i -= 54
		return _Preprocessor_name_3[_Preprocessor_index_3[i]:_Preprocessor_index_3[i+1]]
	default:
		return "Preprocessor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
